language: java
script:
    - cd matsim ; mvn test -B -Dmaven.test.redirectTestOutputToFile
    - cd contrib ; mvn test -B -Dmaven.test.redirectTestOutputToFile
env:
  global:
    - MAVEN_OPTS="-XX:MaxPermSize=1g -Xmx4g"
