language: java
script:
  - cd ${TRAVIS_BUILD_DIR}/playgrounds/dziemke/src/test/java && mvn test -B -Dmaven.test.redirectTestOutputToFile
env:
  global:
    - MAVEN_OPTS="-XX:MaxPermSize=1g -Xmx2g"
    
