language: java
jdk: oraclejdk8
install: mvn clean
script:
  - cd ${TRAVIS_BUILD_DIR}/matsim && mvn install -DskipTests # the hybridsim needs this.  or something else
  - cd ${TRAVIS_BUILD_DIR}/contribs && mvn install -DskipTests # Many of the playgrounds need some of the contribs
  - cd ${TRAVIS_BUILD_DIR}/${MODULE} && mvn test --fail-at-end -B -Dmaven.test.redirectTestOutputToFile -Dmatsim.preferLocalDtds=true
env:
  global:
    - MAVEN_OPTS="-XX:MaxPermSize=1g -Xmx2g"
  matrix:
    - MODULE=matsim
    - MODULE=contribs
    - MODULE=playgrounds
